FROM gradle:8.5-jdk17 AS build

WORKDIR /app

COPY build.gradle settings.gradle /app/
COPY src /app/src

RUN gradle build -x test

FROM openjdk:17

WORKDIR /app

COPY --from=build /app/build/libs/* app.jar

EXPOSE 8060

CMD ["java", "-jar", "app.jar"]